name: vishka_front_v3
description: "Flutter app vishka-burger."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  logger: ^2.6.1
  intl: ^0.20.2
  freezed_annotation: ^3.1.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0
  json_annotation: ^4.9.0
  injectable: ^2.5.1
  sqflite: ^2.4.2
  equatable: ^2.0.7
  url_launcher: ^6.3.2
  intl_phone_field: ^3.2.0
  qr_flutter: ^4.1.0
  auto_route: ^10.1.2
  connectivity_plus: ^6.1.5
  path: ^1.9.1
  modal_bottom_sheet: ^3.0.0
  google_fonts: ^6.3.1
  zoom_tap_animation: ^1.1.0
  mask_text_input_formatter: ^2.9.0
  pinput: ^5.0.2
  story_view: ^0.16.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  injectable_generator: ^2.8.1
  auto_route_generator: ^10.2.4
  json_serializable: ^6.11.1
  freezed: ^3.2.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - .env

flutter_intl:
  enabled: true
